---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/rh-hemartin/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-minio-dev-replicas
