---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/rh-hemartin/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-kubearchive-vacuum
